### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by pavelbinar** [jaredhanson/passport-http-bearer#24]
I think it is because if new version of Express.js and its new way is creating and configuring server.

```
node app.js
/Users/pavelbinar/git/pavelbinar/email-analytics/passport-http-bearer/examples/bearer/app.js:76
var app = express.createServer();
                  ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/pavelbinar/git/pavelbinar/email-analytics/passport-http-bearer/examples/bearer/app.js:76:19)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
    at node.js:807:3
```

**Comment by kuldeeparora** [comment]
express.createServer() is deprecated, express applications no longer inherit from http.Server. please use<br>
var express = require("express");
  var app = express();

**Comment by jaredhanson** [comment]
Express 4.x example is here: https://github.com/passport/express-4.x-http-bearer-example
