### ISSUE TITLE
passport-http-bearer doesn’t work with NestJS: TypeError: Class extends value undefined is not a constructor or null at PassportStrategy

### ISSUE THREAD

**Issue by Joyescat** [jaredhanson/passport-http-bearer#63]
I’m trying to use `passport-http-bearer` in my nestjs project. I need this package for my auth flow.
But `passport-http-bearer` seems incompatible with NestJS.

### Expected behavior

The application should start without any error.

### Actual behavior
When I start my application, I get the following error:

```ts
[11:36:00 AM] File change detected. Starting incremental compilation...

[11:36:01 AM] Found 0 errors. Watching for file changes.


/home/jpellat/passport-bux/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:15
    class MixinStrategy extends Strategy {
                                ^
TypeError: Class extends value undefined is not a constructor or null
    at PassportStrategy (/home/jpellat/passport-bux/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:15:33)
    at Object.<anonymous> (/home/jpellat/passport-bux/project-name/src/strategy.ts:4:47)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jpellat/passport-bux/project-name/src/app.module.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

### Steps to reproduce

1. Create a nestjs project with the cli
```bash
$ npm i -g @nestjs/cli
$ nest new project-name
```

2. Install dependencies `npm i --save @nestjs/core @nestjs/common @nestjs/passport rxjs reflect-metadata passport-http-bearer`

3.   Create the file **strategy.ts** in `src/` directory

```ts
import { PassportStrategy } from '@nestjs/passport';
import { BearerStrategy } from 'passport-http-bearer';

export class Strategy extends PassportStrategy(BearerStrategy, 'okta') {
  constructor() {
    super();
  }

  validate(payload: string): any {
    console.log(payload);
    return payload;
  }
}

``` 

4. Add the following lines in **main.ts**
```ts
import { NestFactory } from '@nestjs/core';
import * as passport from 'passport';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.use(passport.initialize());
  await app.listen(3000);
}
bootstrap();
```

5. Add the new Stratgy as provider to the **AppModule.ts**

```ts
import { Module } from '@nestjs/common';

import { AppController } from './app.controller';
import { AppService } from './app.service';
import { Strategy } from './strategy';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService, Strategy],
})
export class AppModule {}
```

6. start the application `npm run start` or `npm run start:dev`

### Environment

* Operating System: `Windows 10 - WSL2 Ubuntu 20.04.3 LTS (Focal Fossa)`
* node version: `v14.17.5`
* nestjs version: `@nestjs/core@8.1.1`
* passport version: 
```
└─┬ @nestjs/passport@8.0.1
  └── passport@0.4.1
```
* passport-http-bearer version: `passport-http-bearer@1.0.1`

**Comment by jaredhanson** [comment]
Based on the error, this issue should be filed on [nestjs/passport](https://github.com/nestjs/passport).
